from django.urls import path

from . import views

app_name = "api"

urlpatterns = [
    path("health", views.health_check, name="health"),
    path("auth/login", views.login, name="login"),
    path("auth/register", views.register, name="register"),
    path("auth/me", views.get_me, name="me"),
    path("admin/users", views.admin_users, name="admin-users"),
    path("admin/users/<int:user_id>", views.admin_user_detail, name="admin-user-detail"),
    path("admin/users/<int:user_id>/toggle", views.admin_toggle_user, name="admin-toggle-user"),
    path("admin/users/<int:user_id>/reset-password", views.admin_reset_password, name="admin-reset-password"),
    path("admin/cbos", views.admin_list_cbos, name="admin-cbos"),
    path("admin/profissionais", views.admin_profissionais, name="admin-profissionais"),
    path("admin/profissionais/<int:profissional_id>", views.admin_profissional_delete, name="admin-profissional-delete"),
    path("admin/database-overview", views.admin_database_overview, name="admin-database-overview"),
    path("admin/historico-extracoes", views.admin_historico_extracoes, name="admin-historico-extracoes"),
    path("admin/fix-encoding", views.admin_fix_encoding, name="admin-fix-encoding"),
    path("admin/delete-data", views.admin_delete_data, name="admin-delete-data"),
    path("admin/dashboard/stats", views.admin_dashboard_stats, name="admin-dashboard-stats"),
    path("dashboard/stats", views.dashboard_stats, name="dashboard-stats"),
    path("bpa/stats", views.bpa_stats, name="bpa-stats"),
    path("profissionais", views.profissionais, name="profissionais"),
    path("profissionais/<str:cns>", views.profissional_detail, name="profissional-detail"),
    path("pacientes/search", views.pacientes_search, name="pacientes-search"),
    path("pacientes", views.pacientes_create, name="pacientes-create"),
    path("pacientes/<str:cns>", views.paciente_detail, name="paciente-detail"),
    path("procedures/search", views.procedures_search, name="procedures-search"),
    path("procedimentos/search", views.procedures_search, name="procedimentos-search"),
    path("procedimentos/<str:codigo>", views.procedimento_detail, name="procedimento-detail"),
    path("bpa/inconsistencies", views.bpa_inconsistencies, name="bpa-inconsistencies"),
    path("bpa/individualizado", views.bpa_individualizado, name="bpa-individualizado"),
    path("bpa/individualizado/<int:record_id>", views.bpa_individualizado_detail, name="bpa-individualizado-detail"),
    path("bpa/consolidado", views.bpa_consolidado, name="bpa-consolidado"),
    path("export", views.export_bpa, name="export"),
    path("export/list", views.export_list, name="export-list"),
    path("export/download/<str:filename>", views.export_download, name="export-download"),
    path("export/reset", views.export_reset, name="export-reset"),
    path("julia/import", views.julia_import, name="julia-import"),
    path("julia/check-connection", views.julia_check_connection, name="julia-check"),
    path("referencias/raca-cor", views.referencias_raca_cor, name="ref-raca-cor"),
    path("referencias/sexo", views.referencias_sexo, name="ref-sexo"),
    path("referencias/carater-atendimento", views.referencias_carater, name="ref-carater"),
    path("sigtap/competencias", views.sigtap_competencias, name="sigtap-competencias"),
    path("sigtap/competencias/<str:competencia>/activate", views.sigtap_activate_competencia, name="sigtap-activate"),
    path("sigtap/procedimentos", views.sigtap_procedimentos, name="sigtap-procedimentos"),
    path("sigtap/estatisticas", views.sigtap_estatisticas, name="sigtap-estatisticas"),
    path("sigtap/registros", views.sigtap_registros, name="sigtap-registros"),
    path("reports/generate", views.reports_generate, name="reports-generate"),
    path("reports/download/<str:folder>/<str:filename>", views.reports_download, name="reports-download"),
    path("reports/list", views.reports_list, name="reports-list"),
    path("biserver/test-connection", views.biserver_test_connection, name="biserver-test"),
    path("biserver/extract", views.biserver_extract, name="biserver-extract"),
    path("biserver/extract-profissionais", views.biserver_extract_profissionais, name="biserver-extract-profissionais"),
    path("biserver/count", views.biserver_count, name="biserver-count"),
    path("biserver/extract-and-separate", views.biserver_extract_and_separate, name="biserver-extract-and-separate"),
    path("biserver/extract-all", views.biserver_extract_all, name="biserver-extract-all"),
    path("biserver/extract-pacientes", views.biserver_extract_pacientes, name="biserver-extract-pacientes"),
    path("biserver/export-options", views.biserver_export_options, name="biserver-export-options"),
    path("consolidation/execute", views.consolidation_execute, name="consolidation-execute"),
    path("consolidation/verify-procedure/<str:codigo>", views.consolidation_verify_procedure, name="consolidation-verify"),
    path("consolidation/stats", views.consolidation_stats, name="consolidation-stats"),
]
